easy_admin:
   site_name: 'AADL'
   entities:
      User:
         class: App\Entity\User
         list:
            fields:
               - username
               - email
               - enabled
               - lastLogin
               - roles
         form:
            fields:
               - username
               - email
               - enabled
               - lastLogin
               # if administrators are allowed to edit users' passwords and roles, add this:
               - { property: 'plainPassword', type: 'text', type_options: { required: false } }
               - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }

